graph TD
     A["<b>STRUKTUR ORGANISASI</b><br>Tahun 2024 - 2029"] -- KETUA --> B("Masrianto")
              B -- SEKRETARIS --> D["Bambang"]
              B -- BENDAHARA --> E["Bimbing"]
              B -- PENGAWAS --> F["Bumbung"]
